2015-05-07 19:38:57,096 INFO: microblog startup [in /home/pattisdr/microblog/app/__init__.py:26]
2015-05-07 19:39:11,783 ERROR: Exception on /edit [POST] [in /home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/pattisdr/microblog/app/views.py", line 78, in edit
    if form.validate_on_submit():
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/pattisdr/microblog/app/forms.py", line 22, in validate
    user = User.query.filter_by(nickname=self.nickname.data).first()
NameError: global name 'User' is not defined
2015-05-07 19:39:29,828 ERROR: Exception on /edit [POST] [in /home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/pattisdr/microblog/app/views.py", line 78, in edit
    if form.validate_on_submit():
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/pattisdr/microblog/app/forms.py", line 22, in validate
    user = User.query.filter_by(nickname=self.nickname.data).first()
NameError: global name 'User' is not defined
2015-05-07 19:40:21,246 INFO: microblog startup [in /home/pattisdr/microblog/app/__init__.py:26]
2015-05-07 19:40:32,312 ERROR: Exception on /edit [POST] [in /home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/pattisdr/microblog/app/views.py", line 78, in edit
    if form.validate_on_submit():
  File "/home/pattisdr/microblog/flask/local/lib/python2.7/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/pattisdr/microblog/app/forms.py", line 22, in validate
    user = User.query.filter_by(nickname=self.nickname.data).first()
NameError: global name 'User' is not defined
2015-05-07 19:43:16,142 INFO: microblog startup [in /home/pattisdr/microblog/app/__init__.py:26]
2015-05-07 19:46:52,767 INFO: microblog startup [in /home/pattisdr/microblog/app/__init__.py:26]
2015-05-07 19:47:34,742 INFO: microblog startup [in app/__init__.py:26]
